# Generated by Django 3.2.6 on 2021-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=250)),
                ('option_one', models.CharField(max_length=250)),
                ('option_two', models.CharField(max_length=250)),
                ('option_three', models.CharField(max_length=250)),
                ('option_four', models.CharField(max_length=250)),
                ('option_one_votes', models.IntegerField(default=0)),
                ('option_two_votes', models.IntegerField(default=0)),
                ('option_three_votes', models.IntegerField(default=0)),
                ('option_four_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
