# Generated by Django 3.2.6 on 2021-09-26 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_pollquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
